/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Evenements Dev Portal",
  "tagline": "Architecture, contrats, backlog et sprints dans un portail visuel unique.",
  "url": "http://localhost",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "favicon": "data:image/svg+xml,<svg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 64 64%27><rect rx=%2714%27 width=%2764%27 height=%2764%27 fill=%27%230f172a%27/><path d=%27M18 18h28v8H18zm0 14h20v8H18zm0 14h28v8H18z%27 fill=%27%23f8fafc%27/></svg>",
  "organizationName": "mourad244",
  "projectName": "evenements",
  "deploymentBranch": "gh-pages",
  "i18n": {
    "defaultLocale": "fr",
    "locales": [
      "fr"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "themes": [
    "@docusaurus/theme-mermaid",
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "indexDocs": true,
        "docsDir": [
          "../../docs"
        ],
        "indexBlog": false,
        "blogDir": [],
        "indexPages": true,
        "docsRouteBasePath": [
          "reference"
        ],
        "hashed": true,
        "explicitSearchResultPath": true,
        "highlightSearchTermsOnTargetPage": true
      }
    ]
  ],
  "markdown": {
    "mermaid": true,
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "../../docs",
          "routeBasePath": "reference",
          "sidebarPath": "/home/mourad/git_workspace_work/evenements/apps/docs-portal/sidebars.js",
          "editUrl": "https://github.com/mourad244/evenements/tree/main/",
          "breadcrumbs": true,
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false
        },
        "blog": false,
        "theme": {
          "customCss": "/home/mourad/git_workspace_work/evenements/apps/docs-portal/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "data:image/svg+xml,<svg xmlns=%27http://www.w3.org/2000/svg%27 width=%271200%27 height=%27630%27><rect fill=%27%23f8fafc%27 width=%271200%27 height=%27630%27/><circle fill=%27%23dbeafe%27 cx=%27160%27 cy=%27120%27 r=%2790%27/><circle fill=%27%23fed7aa%27 cx=%271030%27 cy=%27110%27 r=%2780%27/><rect fill=%27%230f172a%27 x=%27105%27 y=%27155%27 rx=%2732%27 width=%27990%27 height=%27310%27/><text x=%27155%27 y=%27280%27 font-size=%2754%27 font-family=%27Space Grotesk, sans-serif%27 fill=%27white%27>Evenements Dev Portal</text><text x=%27155%27 y=%27340%27 font-size=%2728%27 font-family=%27Space Grotesk, sans-serif%27 fill=%27%23cbd5e1%27>Architecture, contrats, backlog et sprints</text></svg>",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "Evenements Portal",
      "items": [
        {
          "to": "/",
          "label": "Accueil",
          "position": "left"
        },
        {
          "to": "/architecture",
          "label": "Architecture",
          "position": "left"
        },
        {
          "to": "/api",
          "label": "API",
          "position": "left"
        },
        {
          "to": "/backlogs",
          "label": "Backlogs",
          "position": "left"
        },
        {
          "to": "/sprints",
          "label": "Sprints",
          "position": "left"
        },
        {
          "to": "/services",
          "label": "Services",
          "position": "left"
        },
        {
          "to": "/workflows",
          "label": "Workflows",
          "position": "left"
        },
        {
          "to": "/ideas",
          "label": "Ideas",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "sidebarId": "referenceSidebar",
          "label": "Reference",
          "position": "left"
        },
        {
          "href": "https://github.com/mourad244/evenements",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Portail",
          "items": [
            {
              "label": "Accueil",
              "to": "/"
            },
            {
              "label": "Architecture",
              "to": "/architecture"
            },
            {
              "label": "API",
              "to": "/api"
            }
          ]
        },
        {
          "title": "Reference",
          "items": [
            {
              "label": "Documentation index",
              "to": "/reference/navigation"
            },
            {
              "label": "MVP scope",
              "to": "/reference/mvp-scope"
            },
            {
              "label": "Sprint 1 tracker",
              "to": "/reference/sprints/sprint-1-tracker"
            }
          ]
        },
        {
          "title": "Projet",
          "items": [
            {
              "label": "Repository",
              "href": "https://github.com/mourad244/evenements"
            }
          ]
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
